In [ ]:
#part1
import numpy as np
def array_factory(mode, shape, value=None):
    """
    Creates various NumPy arrays based on the mode.
    - 'zeros': Array filled with 0.
    - 'ones': Array filled with 1.
    - 'full': Array filled with a specified value.
    - 'identity': A square identity matrix of size 'shape'.
    """
    if mode == "zeros":
        return np.zeros(shape)
    elif mode == "ones":
        return np.ones(shape)
    elif mode == "full":
        return np.full(shape, value)
    elif mode == "identity":
        return np.eye(shape)

In [2]:
print(array_factory("zeros", (2, 3)))

[[0. 0. 0.]
 [0. 0. 0.]]


In [3]:
print(array_factory("ones", (3, 3)))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [4]:
print(array_factory("full", (2, 3), 5))

[[5 5 5]
 [5 5 5]]


In [5]:
print(array_factory("identity", 3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#part2
def secure_reshape_and_stack(data1, data2, new_shape):
    """
    1. Validates and converts inputs to NumPy arrays.
    2. Reshapes the first dataset to a specific dimension.
    3. Vertically stacks both datasets into one matrix.
    """
    try:
        arr1 = np.array(data1)
        arr2 = np.array(data2)
        arr1 = arr1.reshape(new_shape)
        combined_data = np.vstack((arr1, arr2))

        return combined_data

    except ValueError as e:
        raise ValueError(f"Company-grade Error: {e}")

In [7]:
data1 = [1, 2, 3, 4]
data2 = [[5, 6],
         [7, 8]]
print(secure_reshape_and_stack(data1, data2, (2, 2)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
